### ISSUE TITLE
update travis

### ISSUE THREAD

**Issue by ralphtheninja** [doowb/npm-api-dependents#3]

**Comment by doowb** [comment]
I usually use [update](https://github.com/update/update) and [updater-travis](https://github.com/update/updater-travis) for travis specifically. I can do this once #2 is merged since I'll also be doing some other maintenance.

**Comment by ralphtheninja** [comment]
You guys have so many cool modules. This is automation madness :grinning:

**Comment by jonschlinkert** [comment]
> automation madness

Lol I might change the `update` description to this
